Aruco marker Dection implenation.
Danryg/DAT295-Railway-Inspection-System pull request #65
Opened 2024-12-18 16:24 UTC by AnsalAntony

Aruco Marker Detection Implementation

    Implemented Aruco marker detection using the ros2_aruco library package.
    Successfully launched the Aruco marker detection and associated topics:
        /aruco_poses (type: geometry_msgs.msg.PoseArray)
        /aruco_markers (type: ros2_aruco_interfaces.msg.ArucoMarkers)

Dependencies:

    OpenCV (version 4.6.0.66): Ensure the correct version is installed to avoid errors.
        Install with: pip3 install opencv-contrib-python

This update allows for efficient Aruco marker detection and topic publishing for better integration

2024-12-18 18:48 UTC, griimmm requested changes
reverting to 4.6 for opencv breaks some dependencies.

check for update to 4.7 + opencv (preferably 4.10)

2025-01-03 17:46 UTC, AnsalAntony reviewed
Updated ArUco marker support for OpenCV 4.7+ compatibility.

- Updated marker branch in the .gitmodules file.
- Modified marker launch Python and YAML files for compatibility with camera and image topics.
- Included `camera/camera_info` and relevant image topics for seamless integration.

2025-01-19 22:34 UTC, griimmm commented
Has to be updated again 
i still see wrong topic in the subscription

2025-01-21 22:46 UTC, griimmm approved these changes
ill merge and make other changes for docking locally

2025-01-21 22:47 UTC, merged